-- Question 1
CREATE TABLE COVID (
	State CHAR(2) PRIMARY KEY,
	Known_White INT,
	Known_Black INT
);

INSERT INTO COVID VALUES ('AZ', 5195, 773);
INSERT INTO COVID VALUES ('CA', 16402, 4298);
INSERT INTO COVID VALUES ('CO', 9281, 1580);
INSERT INTO COVID VALUES ('CT', 14814, 5573);
INSERT INTO COVID VALUES ('GA', 12264, 15559);
INSERT INTO COVID VALUES ('IL', 24128, 20506);

-- Question 2
INSERT INTO COVID VALUES ('MI', 21472, 17990);
INSERT INTO COVID VALUES ('MN', 8995, 5797);

-- Question 3
SELECT State, Known_White, Known_Black, 
	Known_White + Known_Black) AS Total
FROM COVID;

-- Question 4
SELECT *
FROM COVID
WHERE Known_White > 10000;

-- Question 5
SELECT *
FROM COVID
WHERE State LIKE 'C%';

-- Question 6
CREATE TABLE COVID_Asian (
    State CHAR(2) PRIMARY KEY,
    Known_Asian INT
);

INSERT INTO COVID_Asian VALUES ('AZ', 230);
INSERT INTO COVID_Asian VALUES ('CA', 7387);
INSERT INTO COVID_Asian VALUES ('CO', 719);
INSERT INTO COVID_Asian VALUES ('CT', 633);
INSERT INTO COVID_Asian VALUES ('GA', 704);
INSERT INTO COVID_Asian VALUES ('IL', 3556);
INSERT INTO COVID_Asian VALUES ('MI', 1109);
INSERT INTO COVID_Asian VALUES ('MN', 1556);

SELECT c.State, c.Known_White, c.Known_Black, a.Known_Asian
FROM COVID c
JOIN COVID_Asian a
ON c.State = a.State;
